In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movies_data = pd.read_csv('/content/movies.csv')

In [ ]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...     162   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...     169   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...     148   
3  Following the death of District Attorney Harve...  112.312950  ...     165   
4  John Carter is a war-weary, former military ca...   43.926995  ...     132   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
movies_data.shape

(729, 24)

In [ ]:
#selecting the features
selected_features = ['genres' , 'keywords', 'tagline' , 'cast', 'director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [ ]:
movies_data.isnull().sum()

index                     0
budget                    0
genres                    0
homepage                312
id                        0
keywords                  7
original_language         0
original_title            0
overview                  0
popularity                0
production_companies      0
production_countries      0
release_date              0
revenue                   0
runtime                   0
spoken_languages          0
status                    0
tagline                  20
title                     0
vote_average              0
vote_count                0
cast                      0
crew                      1
director                  0
dtype: int64

In [ ]:
#replacing null values
for i in selected_features:
  movies_data[i] = movies_data[i].fillna('') #when there are multiple features


In [ ]:
#combining the features
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']
print(combined_features)

0      Action Adventure Fantasy Science Fiction cultu...
1      Adventure Fantasy Action ocean drug abuse exot...
2      Action Adventure Crime spy based on novel secr...
3      Action Crime Drama Thriller dc comics crime fi...
4      Action Adventure Science Fiction based on nove...
                             ...                        
724    Action Drama Thriller Crime mexico cia kidnapp...
725    Comedy Family father son relationship parents ...
726    Comedy Crime informant jumping from a rooftop ...
727    Family Comedy holiday christmas party santa cl...
728    Fantasy Action Science Fiction black magic fis...
Length: 729, dtype: object


In [ ]:
v = TfidfVectorizer()

In [ ]:
feature_vectors = v.fit_transform(combined_features)
print(feature_vectors)

In [ ]:
#finding the similarity using cosine similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)

[[1.         0.06232851 0.03394713 ... 0.0050107  0.         0.0288348 ]
 [0.06232851 1.         0.02700888 ... 0.01334382 0.01351851 0.02103366]
 [0.03394713 0.02700888 1.         ... 0.01424466 0.03770737 0.00362831]
 ...
 [0.0050107  0.01334382 0.01424466 ... 1.         0.03253733 0.03244655]
 [0.         0.01351851 0.03770737 ... 0.03253733 1.         0.        ]
 [0.0288348  0.02103366 0.00362831 ... 0.03244655 0.         1.        ]]
(729, 729)


In [ ]:
movie_name = input('Enter a movie name: ')

Enter a movie name: batman


In [ ]:
#creating a list with all the movies given in the dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
find_close_match = difflib.get_close_matches(movie_name , list_of_all_titles)
print(find_close_match)

['Catwoman']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Catwoman


In [ ]:
#index of the movie with title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

303


In [ ]:
#based on index values
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.003786749318692379), (1, 0.0033614531063075504), (2, 0.01829179043226519), (3, 0.10857915651966515), (4, 0.03103389157385462), (5, 0.003865726865823218), (6, 0.0), (7, 0.004113846226694305), (8, 0.0), (9, 0.07062228340021316), (10, 0.07937270392173218), (11, 0.014570663282828647), (12, 0.004084314408671391), (13, 0.003457469820742283), (14, 0.07113630558219275), (15, 0.0), (16, 0.003976831211504625), (17, 0.003727887165471395), (18, 0.017376796008896647), (19, 0.0035086153429607267), (20, 0.03907138200176589), (21, 0.003304184215591979), (22, 0.0), (23, 0.0), (24, 0.0032473391838204906), (25, 0.03772525238911107), (26, 0.004074788739236216), (27, 0.003594094390761118), (28, 0.003867105258227064), (29, 0.003986835265508587), (30, 0.018526868709845695), (31, 0.0038504900671854523), (32, 0.013683896473326448), (33, 0.08610954740655628), (34, 0.0), (35, 0.03511052607100554), (36, 0.0038439313804885644), (37, 0.015551055264816767), (38, 0.040447294264047404), (39, 0.00365214200352506

In [ ]:
sorted_similar_movies = sorted(similarity_score , key = lambda x:x[1] , reverse = True)
print(sorted_similar_movies)

[(303, 1.0000000000000002), (608, 0.14274636826738665), (567, 0.11564079963366951), (3, 0.10857915651966515), (506, 0.10732624496791915), (468, 0.10228388492449494), (347, 0.10176077759309982), (119, 0.10162227221530877), (65, 0.0973837663301878), (210, 0.09139358299010512), (511, 0.08892941135346556), (440, 0.08869805467511878), (163, 0.08804700125794714), (549, 0.08782378454406603), (428, 0.08694774035499456), (527, 0.086466003114192), (33, 0.08610954740655628), (299, 0.08431251194724101), (72, 0.08400130289375751), (41, 0.08212715168019272), (207, 0.08186442701782316), (46, 0.07979785390486663), (10, 0.07937270392173218), (301, 0.078571724372892), (487, 0.07849459623427417), (203, 0.07512069512623218), (441, 0.07291139038232104), (147, 0.072686514657982), (14, 0.07113630558219275), (9, 0.07062228340021316), (234, 0.07034330421430424), (442, 0.06732745249249097), (237, 0.06698338034616423), (298, 0.06290419143177295), (588, 0.058360700882532576), (568, 0.054540902844280745), (195, 0.

In [ ]:
print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data.iloc[index]['title']
  if (i<5):
    print(i , '.' , title_from_index)
    i+=1

Movies suggested for you: 

1 . Catwoman
2 . Basic Instinct 2
3 . Runaway Bride
4 . The Dark Knight Rises
